title: Welcome to Hotel Transylvania!

description: I don't say 'bluh bluh-bluh!' Oh, also this page is for module 5 of my Version Control class at Boise State University. But the Hotel Transylvania reference is more funny.

theme: jekyll-theme-hacker
