title: Welcome to Hotel Transylvania!

description: I don't say 'bluh bluh-bluh!' Oh, also this page is for module 5 of my Version Control class at Boise State University and I have a more detailed template for use in industry that I worked on with a friend so it's not permissable for this assignment. But the Hotel Transylvania reference is more funny.

theme: jekyll-theme-hacker
